openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Répond "pong" pour vérifier que l'API fonctionne.
      responses: 
      200:
          description: Succès, retourne "pong"
          content:
            text/plain:
              schema:
                type: string
                example: pong