openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: retourne"pong" si ça fonctionne.
      responses:
        200:
          description: retourne "pong"
          content:
            text/plain:
              schema:
                type: string
                example: pong